IA & Data science (LU3IN0226) -- 2022-2023
--------
*&copy; Equipe pédagogique: Christophe Marsala, Olivier Schwander, Jean-Noël Vittaut.*

<font size="+1" color="RED"><b>[Q]</b></font> <font size="+1"><b>Indiquer dans la boîte ci-dessous vos noms et prénoms :</b></font>

Samy(Adem) YAZID & Alex XU

Ce projet peut être fait en binôme (d'un même groupe). Le nom de chaque membre du binôme doit être indiqué, et un seul rendu sur un des deux comptes Moodle doit être fait.

Les groupes de plus de 2 personnes ne sont pas autorisés.

<font color="RED" size="+1"><b>[Q]</b></font> **Renommer ce fichier ipython**

Tout en haut de cette page, cliquer sur <tt>projet-1</tt> et rajouter à la suite de <tt>projet-1</tt> les noms des membres du binômes séparés par un tiret.

<font color="RED" size="+1">IMPORTANT: soumission de votre fichier final</font>

**Nom à donner au notebook** : *projet-1-Nom1_Nom2.ipynb* 
- *Nom1* et *Nom2* : noms des membres du binôme

**Le compte-rendu doit être rendu sur la page Moodle.**

# Projet 1 - février-mars 2023


<font size="+1" color="RED"><b>Date de rendu : jeudi 22 mars, 18h au plus tard</b></font>
<br />


Vous devez compléter ce notebook en rajoutant vos expérimentations avec vos algorithmes d'apprentissage sur les 2 datasets fournis dans le répertoire data-projet:
- les données data-2D.pkl : données en 2 dimensions, 2 labels
- les données data-5D.pkl : données en 5 dimensions, 2 labels

## Travail à faire

Pour chaque ensemble de données:
- les 3 algorithmes d'apprentissage knn, perceptron et perceptron biais doivent être expérimentés et comparés (ATTENTION: on ne veut que des algorithmes que vous avez implémentés vous-même dans cette UE).
- des résultats d'expérimentations doivent fournir une comparaison des taux de bonne classification apprentissage / test avec validation croisée en 10.
- des courbes (coût, poids, variation d'accuracy,...) doivent être fournies pour étudier les modèles construits.

Vos **expérimentations doivent être expliquées**... (utilisez des boîtes Markdown pour saisir vos explications):
- une argumentation du type *"pourquoi vous avez fait cette expérimentation"* doit être fournie;
- une analyse succincte du résultat fourni doit être aussi donnée.



Par exemple (indicatif): choix de $k$ pour le knn:
- argumentation : pour décider quelle peut être la valeur de $k$ optimale, on décide de tester plusieurs valeurs différentes et de comparer les taux de bonne classification sur la base de test obtenus.
- analyse du résultat: on remarque que la valeur $k$ suivante fournie le meilleur résultat.
- étude du temps d'exécution.


## Travail à rendre
Ce qui doit être rendu : un fichier archive (`.tar`, `.tgz`, ou `.zip` uniquement) contenant uniquement ce notebook, dans lequel vous avez reporté toutes les fonctions que vous utilisez : ce notebook doit pouvoir être exécuté sans autre apport (pensez à vous en assurer avant de le rendre). Les fichiers de données ne doivent pas être inclus dans votre archive !



## Lecture des pickles



In [20]:
# Importation de librairies standards:
import numpy as np
import pandas as pd
import random as random
import matplotlib.pyplot as plt
import sys
sys.path.append('../')

# Importation de la librairie iads
import iads as iads
from iads import Classifiers as classif
from iads import utils as ut

# Importation de la librairie pickle
import pickle as pkl

# lecture des donnéees en dimension 2 dans un dataframe pandas
data2D = pkl.load(open('data-projet/data-2D.pkl', 'rb')) 
X2D = np.array(data2D[['x1', 'x2']], dtype=float) # conversion de type pour une meilleure compatibilité
Y2D = np.array(data2D['label'], dtype=float)

# pour les données en dimension 5, la méthode est la même, modifier seulement les noms des colonnes
data5D = pkl.load(open('data-projet/data-5D.pkl', 'rb')) 
X5D = np.array(data5D[['x1', 'x2']], dtype=float) # conversion de type pour une meilleure compatibilité
Y5D = np.array(data5D['label'], dtype=float)

ModuleNotFoundError: No module named 'iads'

In [ ]:
data2D[0:5]

x1        x2  label
0  0.830557 -2.250314     -1
1  0.627488 -2.533405     -1
2 -1.279837 -1.630564     -1
3  2.002088 -3.415239     -1
4  3.141847 -0.376081     -1

In [ ]:
X2D[0:5]

array([[ 0.83055692, -2.25031368],
       [ 0.62748844, -2.53340502],
       [-1.27983681, -1.63056446],
       [ 2.00208794, -3.41523902],
       [ 3.14184699, -0.37608089]])

In [13]:
Y2D[0:5]

array([-1., -1., -1., -1., -1.])

In [14]:
data5D[0:5]

x1        x2        x3        x4        x5  label
0 -0.472352 -0.035994  0.572799  2.017446 -1.865967     -1
1  1.993913  0.984667 -1.180237  1.460067 -0.195743     -1
2  0.923188  1.194008  0.065319  0.909784  0.832256     -1
3  2.540148 -0.427836 -0.113014  3.257095 -1.689755     -1
4  4.331413  0.590868 -1.105335  4.475987 -1.790176     -1

In [15]:
X5D[0:5]

array([[-0.4723522 , -0.03599385],
       [ 1.9939134 ,  0.9846668 ],
       [ 0.92318832,  1.19400787],
       [ 2.54014784, -0.42783646],
       [ 4.33141251,  0.59086794]])

In [16]:
Y5D[0:5]

array([-1., -1., -1., -1., -1.])

In [17]:
# Définition des données d'apprentissage (X2D, Y2D)
random.seed(42) 
(train_desc, train_label), (test_desc, test_label) = ut.genere_train_test(X2D, Y2D,75,75)

data_train = train_desc
label_train = train_label
data_test = test_desc
label_test = test_label

NameError: name 'ut' is not defined

In [ ]:
# Perceptron
perceptron = classif.ClassifierPerceptron(256,0.01)

# Apprentissage du perceptron
print("Init perceptron: w= ", perceptron.w)
les_variations = perceptron.train(data_train, label_train, 1000) 
print("Nb iterations: ", len(les_variations))

# Traçage de la courbe des variations
plt.plot(range(1,len(les_variations)+1),les_variations)  
plt.ylabel('Différence')
plt.xlabel("Etape")
plt.show()

print("1vs2 :")
print("Accuracy finale (train): ", perceptron.accuracy(data_train, label_train))
print("Accuracy finale (test) : ", perceptron.accuracy(data_test, label_test))